### PR TITLE
#92 unecessary return values in api requests

### LINKED ISSUE #92: Unecessary return values in api requests
Currently, in most api methods values like `self getObjectFromRequest: aRPModelname with: anId` or `self sendJson: jsonString` are returned. These returns are unnecessary, because mostly an instance of `RPApplication` is returned and not used. This makes the code harder to understand. I would expect the return value to contain a useful value such as a created object or the method not to return anything.

Methods like `self getObjectFromRequest: aRPModelname with: anId` also do not return an object from a request (what I would expect), they append the model with the given class and id to the response in `threadLocal`. We should discuss the naming and usage of these methods.

### PR DESCRIPTION
**Pull request by ninaihde**
fixes #92

### CODE REVIEW

**Comment by richardebeling** [comment]
A quick notice: Github has [Keywords](https://help.github.com/articles/closing-issues-using-keywords/) that connect pull requests and issues. When you write `fixes #issue` somewhere in the PR, the issue will be closed when the PR is accepted and github shows nice linkage between them. We should use that. I added the comment to your first post.

**Comment by richardebeling** [comment]
You now used different naming than any suggestion in #92, including your own. Is there any reason?

**Comment by ninaihde** [comment]
We are talking about ``writeObjectFromGetRequest: aModel with: anId`` and ``writeResponseForGet: aModel with: anId``, right? I have choosen the first one because I had no idea how to rename e.g. ``writeAllModelsFromGetRequestAsHtml`` or ``writeRegisteredObjectsFromGetRequestAsHtml``. This way all methods are called ``writeSomethingSpecificFromGetRequest`` so we can find them quickly. But I don't really like the method names and especially their length now - so I'm open to other suggestions.

**Comment by richardebeling** [comment]
Just from looking at the names, these are my thoughts:

I think "ForGet" is more unintuitive than "FromGet". FromGet sounds like you would extract something from the get request, but thats not true. You fetch the object that matches the get request from the database and then answer it. Therefore, you write the response **for** the get request.

I also think that the word "Request" in all your method names does not add any value. `writeAllModelsFromGetRequest` is in my opinion as clear as `writeAllModelsFromGet`.

I think making the last word "id" instead of "with" is shorter and better, since we want an ID to follow.

This would leave us with
- `writeAllModelsForGet`
- `writeAllModelsForGetAsHtml`
- `writeRegisteredModelsForGetAsHtml:`
- `writeObjectForGet:id:`
- `writeObjectForGetAsHtml:id:`
- `writeRegisteredObjectsForGet:`
- `writeRegisteredObjectsForGetAsHtml:`

A get request currently would access /api/ModelName to get all objects and /api/ModelName/id to get the object with the specific id. I think this naming scheme should also be used in the function names. So, in my opinion, the names should be:
- `writeObjectsForGet:`
- `writeObjectForGet:id:`

in order to make them even more similar, we could also think about `writeResponseForGet:` and `writeResponseForGet:id:`, although this is probably hard to get consistent with the other methods, so I'll drop that thought from here.

The "asHtml" should be put after the "Objects" / "Object" since that is what we want to be written as html.

The term "registered" in registeredObjects does not make any sense to me right now. There is nothing "registered" about an object. I think this was copied and pasted from the models, which can be registered in the app.

So, fixing these both, we get (text in parentheses is how I would understand that name)
- `writeAllModelsForGet` (which prints all registered models when you GET /api)
- `writeAllModelsAsHtmlForGet` (which prints all registered models when you GET /html)
- `writeObjectForGet:id:` (which prints the object when you GET /api/ModelClass/id)
- `writeObjectAsHtmlForGet:id:` (which prints the object when you GET /html/ModelClass/id)
- `writeObjectsForGet:` (which prints all objects when you GET /api/ModelClass)
- `writeObjectsAsHtmlForGet:` (which prints all objects when you GET /html/ModelClass)
- `writeRegisteredModelsAsHtmlForGet:` (see below, will be removed)

Now, there is a mismatch. The handler for a GET request on /html/ModelClass is not actually `writeObjectsAsHtmlForGet`, but rather `writeRegisteredModelsAsHtmlForGet:`. This is a handler that first prints a ModelClass's scheme and then all objects in that model class. And it uses what we would now call `writeObjectsAsHtmlForGet` as a helper method to write the objects.

That doesn't make any sense. So, if we want to keep the behaviour that the HTML overview page for a model class has the model classes scheme as well as all objects and if we still want consistent naming, we would have to make `writeObjectsAsHtmlForGet:` behave like `writeRegisteredModelsAsHtmlForGet:` behaves now. The helper function that actually formats the string for all the objects could then be named to whatever is appropriate. It should be somewhat different so you instantly see that it's not a handler though.

If we agree on this, we can talk about how we want to name the POST, PUT and DELETE handlers. I'd name them as similar as possible, hopefully only exchanging the word "Get".

Now, my head hurts and I have a strong urge to finde the person that made the initial naming on these methods and make him / her re-read all of this code. Anyways, I think if we apply the naming scheme I proposed in the last list, I hope it's a bit easier to understand.

**Comment by richardebeling** [comment]
One more point: "AllModels" doesn't have any more information than just "Models", so I'd also remove the "All" there.

- `writeModelsForGet` (which prints all registered models when you GET /api)
- `writeModelsAsHtmlForGet` (which prints all registered models when you GET /html)
- `writeObjectForGet:id:` (which prints the object when you GET /api/ModelClass/id)
- `writeObjectAsHtmlForGet:id:` (which prints the object when you GET /html/ModelClass/id)
- `writeObjectsForGet:` (which prints all objects when you GET /api/ModelClass)
- `writeObjectsAsHtmlForGet:` (which prints all objects when you GET /html/ModelClass)

If it was me to decide, I'd think having the "Get" in the first two is not really important. If you filter these methods by names for "get", you usually want the handler that is called when you get a model or all objects or a specific object. So I'd even further reduce the first two to 
- `writeModels` (which prints all registered models when you GET /api)
- `writeModelsAsHtml` (which prints all registered models when you GET /html)
But I don't think it's that important or really harmful if we leave the Get there.

**Comment by essal0815** [comment]
I agree with your suggestions for naming. Thanks a lot for summing up properly.
I would suggest to wait with merging this PR. This commit is just about renaming. So lets write here all names and do it, after the other both PRs #103 & #101 are merged.
Probably it might be the easiest to start over from develop then and having the list with good names next to Squeak and really just rename.

I think the other Methods (Post,Put,Delete) can be similar, but should imply the change of the dataset somehow.
In `writeModelForPost:` the write could have 2 meanings, writing to Database and writing the response.
Or is this not explicit enough ?
(Maybe something like `#writeNewModelForPost:` and for put: `#writeAndUpdateModelForPut:` )

**Pull request merged**
